sudo: required

git:
  depth: 1

language: node_js

node_js:
  - '10'
  - '11'

dist: xenial
services:
  - xvfb

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - git fetch -a
  - git fetch origin master
  - cd buffet

install:
  - yarn

before_script:
  - git fetch origin master:master

script:
  - yarn run lint
  - yarn run test

cache:
  directories:
    - 'node_modules'
